version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: "elasticsearch-sakenomy"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.name=docker-cluster-sakenomy
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'discovery.zen.ping.unicast.hosts=elasticsearch'
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.4.0
  #   container_name: kibana
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #   restart: always
  #   ports:
  #    - "5601:5601"
  #   networks:
  #     - esnet
  # api:
  #   container_name: 'sakenomy_web_api'
volumes:
  esdata:
    driver: local

networks:
  esnet:
